name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build WAR with Maven
      run: mvn clean package

    - name: Upload WAR file
      uses: actions/upload-artifact@v4
      with:
        name: war-artifact
        path: target/*.war

  security-checks:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Trivy Install
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Trivy FS Scan
      run: trivy fs --format table -o fs-report.json .

    - name: Gitleaks Install
      run: sudo apt install gitleaks -y

    - name: Gitleaks scan
      run: gitleaks detect --source . --report-path=gitleaks-report.json --report-format=json

  selenium-tests:
    runs-on: ubuntu-latest
    needs: build

    services:
      tomcat:
        image: tomcat:9.0
        ports:
          - 8080:8080

    steps:
    - uses: actions/checkout@v4

    - name: Download WAR file from build job
      uses: actions/download-artifact@v4
      with:
        name: war-artifact

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Install Chrome for Testing and ChromeDriver
      run: |
        CHROME_INFO=$(curl -sSL https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)
        DRIVER_URL=$(echo "$CHROME_INFO" | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64") | .url')
        CHROME_URL=$(echo "$CHROME_INFO" | jq -r '.channels.Stable.downloads.chrome[] | select(.platform=="linux64") | .url')

        # Install Chrome
        wget -O chrome-linux.zip "$CHROME_URL"
        unzip chrome-linux.zip
        sudo mv chrome-linux64 /opt/chrome
        sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

        # Install ChromeDriver
        wget -O chromedriver.zip "$DRIVER_URL"
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Verify installation
      run: |
        google-chrome --version
        chromedriver --version

    - name: Install Python dependencies
      run: |
        pip install selenium pytest

    - name: Copy WAR to Tomcat container
      run: |
        CONTAINER_ID=$(docker ps -q --filter ancestor=tomcat:9.0)
        docker cp *.war $CONTAINER_ID:/usr/local/tomcat/webapps/ROOT.war

    - name: Wait for application to be available
      run: |
        echo "Waiting for app to deploy..."
        for i in {1..30}; do
          curl -s http://localhost:8080/ | grep -q "Go to Dashboard" && break
          sleep 2
        done

    - name: Run Selenium Tests (Headless Chrome)
      run: pytest tests/
